import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from 'sonner'
import "./globals.css";
import { SignedIn, SignedOut } from "@clerk/nextjs";
import { Suspense } from 'react';
import Loading from "@/components/loading-button";
import LogoutLink from "@/components/logout-link";
import LoginLink from "@/components/login-link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <body className="antialiased bg-background text-foreground">
          <Suspense fallback={<Loading buttonText="Loading..." variant="outline" />}>
            <SignedIn>
              <div className="relative">

                <div className="absolute top-4 right-4">
                  <LogoutLink />
                </div>
                {children}
              </div>
            </SignedIn>
            <SignedOut>
              <div className="relative">
                <div className="absolute top-4 right-4">
                  <LoginLink />
                </div>
                {children}
              </div>
            </SignedOut>
          </Suspense>

          <Toaster richColors position="top-center" expand={false} closeButton />
        </body>
      </html>
    </ClerkProvider>
  );
}