import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from 'sonner'
import "./globals.css";
import { SignedIn, SignedOut } from "@clerk/nextjs";
import { Suspense } from 'react';
import Loading from "@/components/loading-button";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <body className="antialiased bg-background text-foreground">
          <Suspense fallback={<Loading />}>
            <SignedIn>
              {children}
            </SignedIn>
            <SignedOut>
              {children}
            </SignedOut>
          </Suspense>

          <Toaster richColors position="top-center" expand={false} closeButton />
        </body>
      </html>
    </ClerkProvider>
  );
}